config/routes.rb
Rails.application.routes.draw do
  root 'stories#index'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cards, only: [:index, :show, :new, :create]
  resources :stories, only: [:index, :show, :new, :create] do
    resources :narrations, only: [:create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
  validates :name, presence: true
  mount_uploader :image, ImageUploader
end

app/models/narration.rb
class Narration < ApplicationRecord
  validates :body, presence: true

  belongs_to :story
  belongs_to :user
end

app/models/story.rb
class Story < ApplicationRecord
  validates :name, presence: true
  validates :theme, presence: true

  has_many :narrations
  has_many :users, through: :narrations
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :narrations
  has_many :stories, through: :narrations
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  def index
    @cards = Card.all
  end

  def show
    @card = Card.find(params[:id])
  end

  def new
    @card = Card.new
  end

  def create
    @card = Card.new(card_params)

    if @card.save
      flash[:notice] = "Card created successfully"
      redirect_to cards_path
    else
      flash.now[:error] = @card.errors.full_messages.join(", ")
      render :new
    end
  end

  private
  def card_params
    params.require(:card).permit(:name, :image, :flavor_text)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
end

app/controllers/narrations_controller.rb
class NarrationsController < ApplicationController
  def create
    @story = Story.find(params[:story_id])
    @user = current_user
    @narration = Narration.new(narration_params)
    @narration.story = @story
    @narration.user = @user
    if @narration.save
      flash[:notice] = "Narration created successfully"
      redirect_to story_path(@story.id)
    else
      flash[:error] = @narration.errors.full_messages.join(", ")
      redirect_to story_path(@story.id)
    end
  end

  private
  def narration_params
    params.require(:narration).permit(:body)
  end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  def index
    @stories = Story.all
  end

  def show
    @story = Story.find(params[:id])
    @narrations = Narration.where(story_id: params[:id])
    @narration = Narration.new
  end

  def new
    @story = Story.new
  end

  def create
    @story = Story.new(story_params)

    if @story.save
      flash[:notice] = "Story created successfully"
      redirect_to stories_path
    else
      flash.now[:error] = @story.errors.full_messages.join(", ")
      render :new
    end
  end

  def story_params
    params.require(:story).permit(:name, :theme)
  end
end

app/views/cards/index.html.erb
<h1>Check out all of your cards!</h1>
<ul>
  <% @cards.each do |card| %>
    <li><%= link_to card.name, card_path(card) %></li>
  <% end %>
</ul>
<%= link_to "New Card", new_card_path %>

app/views/cards/new.html.erb
<h1>Make Your Own Card Here!</h1>

<%= form_for(@card) do |f| %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>


  <div class="field">
    <%= f.label :flavor_text %><br />
    <%= f.text_field :flavor_text %>
  </div>

  <%= f.file_field :image %>

  <div class="actions">
    <%= f.submit "Manifest!" %>
  </div>
<% end %>

app/views/cards/show.html.erb
<h1> <%= @card.name %> </h1>
<%= image_tag @card.image.url %>
<p> <%= @card.flavor_text %> </p>

app/views/homes/index.html.erb
<p>
  Modify me in `app/views/homes/index.html.erb` or change the root directive in
  `config/routes.rb`
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CharacterGenerator</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <%= stylesheet_link_tag 'application', media: 'all' %>
  
    <%= javascript_include_tag "vendor/modernizr" %>
  
  <%= csrf_meta_tags %>
</head>
<body>
  
  <nav class="top-bar">
    <ul class="title-area">
      <li class="name">
        <h1><a href="/">CharacterGenerator</a></h1>
      </li>
    </ul>

    <section class="top-bar-section">
      <ul class="right">
        <%- if current_user -%>
          <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
        <%- else -%>
          <li><%= link_to 'Sign Up', new_user_registration_path %></li>
          <li><%= link_to 'Sign In', new_user_session_path %></li>
        <%- end -%>
      </ul>
    </section>
  </nav>

  <%- flash.each do |key, value| -%>
    <div class="flash flash-<%= key %>">
      <%= value %>
    </div>
  <%- end -%>

  <%= yield %>

  <%= javascript_include_tag 'application' %>
  
  <%- if Rails.env.development? || Rails.env.test? -%> 
    <%= javascript_tag do %>
      window.railsEnv = '<%= Rails.env %>'
    <%- end -%>
  <%- end -%>
  <%= javascript_pack_tag 'application' %>
  
  <%= yield :extra_footer %>
</body>
</html>

app/views/stories/index.html.erb
<ul>
  <% @stories.each do |story| %>
    <li><%= link_to story.name, story_path(story) %></li>
  <% end %>
</ul>
<%= link_to "New Story", new_story_path %>
<%= link_to "Check out your cards", cards_path %>

app/views/stories/new.html.erb
<h1>Begin your own story...</h1>

<%= form_for(@story) do |f| %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :theme %><br />
    <%= f.text_field :theme %>
  </div>

  <div class="actions">
    <%= f.submit "Embark!" %>
  </div>
<% end %>

app/views/stories/show.html.erb
<h1> <%= @story.name %> </h1>
<h3> <%= @story.theme %> </h3>

<ul>
  <% @narrations.each do |narration| %>
    <li><%= narration.body %></li>
  <% end %>
</ul>

<%= form_for([@story, @narration]) do |f| %>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_field :body %>
  </div>

  <div class="actions">
    <%= f.submit "Confirm Action" %>
  </div>
<% end %>